version: '3'
services:
  frontend:
    image: package/frontend
    ports:
      - "5173:5173"
    networks:
      - front-tier
      - back-tier
  backend:
    image: package/backend
    ports:
      - "3001:3001"
    networks: 
      - back-tier
networks:
  front-tier: {}
  back-tier: {}